version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="${PLEX_TIMEZONE}"
      - PLEX_CLAIM="${PLEX_CLAIM_TOKEN}"
      - ADVERTISE_IP="${PLEX_ADVERTISE_IP}"
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
    volumes:
      - ~/plex/config:/config
      - ~/plex/transcode:/transcode
      - ~/plex/data:/data
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: unless-stopped
    privileged: true
    ports:
      - 9091:9091
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    volumes:
      - ~/plex/data:/data
      - /etc/localtime:/etc/localtime:ro
  proxy:
    container_name: proxy
    image: haugene/transmission-openvpn-proxy
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - transmission:transmission
