version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="${PLEX_TIMEZONE}"
      - PLEX_CLAIM="${PLEX_CLAIM_TOKEN}"
      - ADVERTISE_IP="${PLEX_ADVERTISE_IP}"
      - PLEX_UID=${UID}
      - PLEX_GID=${GID}
    hostname: ${PLEX_HOST}
    volumes:
      - ~/plex/config:/config
      - ~/plex/transcode:/transcode
      - ~/plex/data:/data
      - ~/plex/movies:/movies
      - ~/plex/tvshows:/tvshows
      - ~/plex/music:/music
      - ~/plex/photos:/photos
      - ~/plex/othervideos:/othervideos
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    ports:
      - 8181:8181
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=Europe/Paris
    volumes:
      - ~/tautulli/config:/config
      - ~/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=Europe/Paris
    volumes:
      - ~/transmission/config:/config
      - ~/transmission/downloads:/downloads
      - ~/transmission/watch:/watch
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PGID=${GID}
      - PUID=${UID}
    volumes:
      - ~/lidarr/data:/config
      - ~/transmission/downloads:/downloads
      - ~/plex/music:/music
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - TZ=Europe/Paris
      - PGID=${GID}
      - PUID=${UID}
    volumes:
      - ~/radarr/config:/config
      - ~/transmission/downloads:/downloads
      - ~/plex/movies:/movies
      - /etc/localtime:/etc/localtime:ro
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/sonarr/config:/config
      - ~/plex/tvshows:/tv
      - ~/transmission/downloads:/downloads
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=Europe/Paris
    volumes:
      - ~/jackett/data:/config
      - ~/jackett/blackhole:/downloads
      - /etc/localtime:/etc/localtime:ro
