version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="${PLEX_TIMEZONE}"
      - PLEX_CLAIM="${PLEX_CLAIM_TOKEN}"
      - ADVERTISE_IP="${PLEX_ADVERTISE_IP}"
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
    hostname: ${PLEX_HOST}
    volumes:
      - ~/plex/config:/config
      - ~/plex/transcode:/transcode
      - ~/plex/data:/data
      - /mnt/movies:/movies
      - ~/plex/tvshows:/tvshows
      - ~/plex/music:/music
      - ~/plex/photos:/photos
      - ~/plex/othervideos:/othervideos
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
    environment:
      - PGID=${TRANSMISSION_PGID}
      - PUID=${TRANSMISSION_PUID}
      - TZ=Europe/Paris
    volumes:
      - ~/transmission/config:/config
      - /mnt/downloads:/downloads
      - ~/transmission/watch:/watch
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PGID=${LIDARR_PGID}
      - PUID=${LIDARR_PUID}
    volumes:
      - ~/lidarr/data:/config
      - /mnt/downloads:/downloads
      - ~/plex/music:/music
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - TZ=Europe/Paris
      - PGID=${RADARR_PGID}
      - PUID=${RADARR_PUID}
    volumes:
      - ~/radarr/config:/config
      - /mnt/downloads:/downloads
      - /mnt/movies:/movies
      - /etc/localtime:/etc/localtime:ro
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PGID=${JACKETT_PGID}
      - PUID=${JACKETT_PUID}
      - TZ=Europe/Paris
    volumes:
      - ~/jackett/data:/config
      - ~/jackett/blackhole:/downloads
      - /etc/localtime:/etc/localtime:ro
