version: "3"
services:
  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ="${PLEX_TIMEZONE}"
      - PUID=${PLEX_UID}
      - PGID=${PLEX_GID}
      - VERSION=latest
    volumes:
      - ~/plex/transcode:/transcode
      - ~/plex/library:/config
      - ~/plex/tvseries:/data/tvshows
      - ~/plex/movies:/data/movies
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
    environment:
      - PGID=${TRANSMISSION_PGID}
      - PUID=${TRANSMISSION_PUID}
      - TZ=Europe/Paris
    volumes:
      - ~/transmission/config:/config
      - ~/transmission/downloads:/downloads
      - ~/transmission/watch:/watch
